const sampleListings =[
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
    title: "Modern Studio in Tokyo",
    description: "Compact yet stylish studio in the heart of Tokyo. Ideal for solo travelers.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 950,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Tropical Bungalow",
    description: "Relax in this tropical bungalow surrounded by palm trees and beaches.",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 1300,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Elegant Paris Apartment",
    description: "Live the Parisian dream in this chic apartment near the Eiffel Tower.",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
    price: 2200,
    location: "Paris",
    country: "France",
  },
  {
    title: "Cozy Cottage in Scotland",
    description: "Warm and welcoming cottage surrounded by the scenic Scottish Highlands.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 700,
    location: "Inverness",
    country: "Scotland",
  },
  {
    title: "Desert Glamping Dome",
    description: "Stay under the stars in this unique desert dome accommodation.",
    image: "https://i.pinimg.com/736x/5b/55/a8/5b55a8545d83215ab7a8c6e48009bcc8.jpg",
    price: 600,
    location: "Wadi Rum",
    country: "Jordan",
  },
  {
    title: "Island Overwater Villa",
    description: "Luxury villa built over the clear blue waters of the Maldives.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9sZDcPPtNQi6s_9Txa8JaYo7Jn_VBzLsDpxKSz1egywqq7pScKlBYxLE21qnLVofTFKw&usqp=CAU",
    price: 5500,
    location: "Male",
    country: "Maldives",
  },
  {
    title: "Countryside Farmhouse",
    description: "Charming farmhouse surrounded by fields and fresh air. Great for family getaways.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 850,
    location: "Bavaria",
    country: "Germany",
  },
  {
    title: "Igloo Adventure",
    description: "Stay in a cozy igloo and experience the northern lights like never before.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 2700,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "City Hostel",
    description: "Budget-friendly hostel with shared facilities and a vibrant atmosphere.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 400,
    location: "Bangkok",
    country: "Thailand",
  },
  {
    title: "Cliffside Retreat",
    description: "Stay on the edge of breathtaking cliffs overlooking the ocean.",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071",
    price: 1800,
    location: "Lisbon",
    country: "Portugal",
  },
];
  module.exports = { data: sampleListings };